# Generated by Django 2.2.3 on 2019-07-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=30)),
                ('Non-Veg', models.BooleanField(default=False)),
                ('d_price', models.IntegerField()),
                ('d_qty', models.IntegerField()),
            ],
            options={
                'db_table': 'Dishes',
            },
        ),
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=30)),
                ('u_dob', models.CharField(max_length=30)),
                ('u_address', models.CharField(max_length=30)),
                ('u_email', models.CharField(max_length=30)),
                ('u_phone', models.IntegerField()),
            ],
            options={
                'db_table': 'User_Details',
            },
        ),
    ]
