# Generated by Django 2.2.3 on 2019-07-30 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodjango', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='Non-Veg',
            new_name='Non_Veg',
        ),
    ]
